### PR TITLE
Update

### PR DESCRIPTION
**Pull request by EmperorPinguin**
Updates existing civilizations according to the description in the LekMOD civilizations master list.

### CODE REVIEW

**Comment by SeventhM** [comment]
2 corrections:
1. The lack of gold on ducal stable for maize was intentional to keep consistency. This is because, as I noted a long while ago on discord, for some reason stables gave maize food which doesn't line up with the idea of what the stable and granary are supposed to do
2. The use of the word "Coastal" for polders does not refer to Coast tiles. It refers to land tiles next to coast tiles

**Comment by EmperorPinguin** [comment]
1. Food or gold for Maize is indeed odd to put on the stable as a unique, but I went by the description in the document. I'll remove it.
2. I misread, it indeed says "coastal" tiles, not "coast". Are you sure this is how the Polder behaves in Lekmod? It would mean you can build them on coastal hills, which doesn't make any sense. Could you test it for me?

**Comment by SeventhM** [comment]
>  Could you test it for me?

I don't currently have a computer to test at unfortunately. Apparently, you might be correct. I kinda missed they added a second "water polder" to the file that can actually be on coast tiles

**Comment by SeventhM** [comment]
Note: the extra food on polders actually applies to flood plains as well, apparently. And lakes?

**Comment by EmperorPinguin** [comment]
The description says +3 food on Marsh, +2 food on coast and lakes. It does not specify how much food they yield on flood plains. I would expect it to be +2, as the flood plain already provides +2 base food.

**Comment by SeventhM** [comment]
In the file, it's land polders give 3 food, water gives 2. Land polder can be on flood plains, marsh, and lakes while water can be on coast and ocean. There's no other clarification on the stats

**Comment by EmperorPinguin** [comment]
Lakes are considered Water in Unciv, is that different in Civ5?

**Comment by SeventhM** [comment]
I don't think it is. It's just weird definitions for the tile in the file

**Pull request merged**
