### PR TITLE
Update Nations.json

### PR DESCRIPTION
**Pull request by Thienanbad**
Because you use modern name for cities so i have to change Hai Bà Trưng into name of Vietnam president after 1975. Some old names you put for cities are province name so i have to change it back

### CODE REVIEW

**Comment by yairm210** [comment]
Looks like you have self conflicts

**Comment by Thienanbad** [comment]
> Looks like you have self conflicts

How to resolve it

**Comment by Thienanbad** [comment]
> Looks like you have self conflicts

What do I need to do next

**Comment by Thienanbad** [comment]
> Looks like you have self conflicts

Oke i have fixed it.

**Pull request merged**
