### PR TITLE
Some icons 

### PR DESCRIPTION
**Pull request by DeStup**
added GW icons, some building, policy, wonder icons.
Updated russian.properties. Oman,Jerusalem,Mexico,Madagasacr,Maya

### CODE REVIEW

**Comment by DeStup** [comment]
I messed up, and mixed up the translation and icon changes. It's all in one PR(

**Comment by SeventhM** [comment]
Not a blocker, but I do want a different Globe Theatre icon that's easier to see. Maybe same for Panama Canal, maybe same for Writing Auditorium

**Comment by DeStup** [comment]
Yes, I don't like the theatrical icon either, but I couldn't find anything better. Maybe I'll draw it later like this one (https://logos.fandom.com/wiki/Shakespeare%27s_Globe?file=Shakespeare%27s_Globe_old.png)

**Comment by SeventhM** [comment]
> Yes, I don't like the theatrical icon either, but I couldn't find anything better. Maybe I'll draw it later like this one

Hmm... Maybe. At least for me, the main thing is ideally icons should be black with white/transparent linework, not white/transparent with black linework like that icon is.

**Pull request merged**
